### PR TITLE
Fix Ubuntu 16.04 AMI build issues, upgrade ENA and ixgbevf

### LINKED ISSUE #4: Permission Denied + ixgbevf build issues with Ubuntu 16.04 AMI
Building from `master` does not complete when building AMIs for Ubuntu 16.04.   

### Issue 1:
Error when building ixgbevf:
```
cd src/; make BUILD_KERNEL=4.4.0-1022-aws....(bad exit status: 2)
ERROR (dkms apport): binary package for ixgbevf: 3.1.2 not found
Error! Bad return status for module build on kernel: 4.4.0-1022-aws (x86_64)
Consult /var/lib/dkms/ixgbevf/3.1.2/build/make.log for more information.
```

I found a fix in [this SO answer](https://stackoverflow.com/a/44833347).

Adding the following line to `/scripts/ec2/networking.sh` (I added to line 104) resolves the issue:
```shell
sed -i 's/#if UTS_UBUNTU_RELEASE_ABI > 255/#if UTS_UBUNTU_RELEASE_ABI > 99255/' /usr/src/ixgbevf-${SRIOV_DRIVER_VERSION}/src/kcompat.h
```

### Issue 2:    
With the above resolved, the AMI builds but when started, #1 is occurring again, this time for `/etc/udev/70-persistent-rules.net`.   cloud-init now calls `write_file` on this file [here](https://github.com/number5/cloud-init/blob/master/cloudinit/net/eni.py#L468) which causes the same issue.     

Applying the fix in #1 to `/scripts/common/clean-up.sh` resolves the issue:
-- line 277
```shell
if [[ $AMAZON_EC2 == 'yes' ]]; then
    # Get rid of this file, alas clout-init will probably
    # create it again automatically so that it can wreck
    # network configuration. These files, sadly cannot be
    # simply a symbolic links to /dev/null, as cloud-init
    # would change permission of the device node to 0644,
    # which is disastrous, every time during the system
    # startup.
    rm -f \
      /etc/network/interfaces.d/50-cloud-init.cfg \
      /etc/systemd/network/50-cloud-init-eth0.link \
      /etc/udev/rules.d/70-persistent-net.rules

    pushd /etc/network/interfaces.d &>/dev/null
    mknod .null c 1 3
    ln -sf .null 50-cloud-init.cfg
    popd &>/dev/null

    pushd /etc/udev/rules.d &>/dev/null
    mknod .null c 1 3
    ln -sf .null 70-persistent-net.rules
    popd &>/dev/null
fi
```

If these fixes are correct, I'm happy to submit a PR - just let me know.    

And, thank you for all of your work here! 

EDIT: Fixed in my fork via [fbb0439](https://github.com/shanonvl/packer-templates#fbb0439)

### PR DESCRIPTION
**Pull request by shanonvl**
Resolves #4.  Please see the issue for details.

### CODE REVIEW

File: scripts/ec2/networking.sh [hunk 1]
```diff
@@ -29,13 +29,13 @@ readonly EC2_FILES='/var/tmp/ec2'
 
 [[ -d $EC2_FILES ]] || mkdir -p $EC2_FILES
 
-# The version 3.1.2 is currently the recommended version.
-SRIOV_DRIVER='ixgbevf-3.1.2.tar.gz'
+# The version 4.2.1 is currently the recommended version.
```
Comment (kwilczynski) [inline scripts/ec2/networking.sh:32]: With this driver version, did you see that the support for the `InterruptThrottleRate` module option/parameter is still there (otherwise it would complain on module load/insertion)? I am not sure if they still have it in the most recent release - in which case we would need to set the value using ethtool (see: https://sourceforge.net/p/e1000/mailman/message/35774103/; for examples).

File: scripts/ec2/networking.sh [hunk 2]
```diff
@@ -29,13 +29,13 @@ readonly EC2_FILES='/var/tmp/ec2'
...
+SRIOV_DRIVER='ixgbevf-4.2.1.tar.gz'
 if [[ -n $SRIOV_DRIVER_VERSION ]]; then
     SRIOV_DRIVER="ixgbevf-${SRIOV_DRIVER_VERSION}.tar.gz"
 fi
 
-ENA_DRIVER='ena_linux_1.1.3.tar.gz'
+ENA_DRIVER='ena_linux_1.2.0.tar.gz'
```
Comment (kwilczynski) [inline scripts/ec2/networking.sh:38]: 👍 

I saw them releasing it recently. I hope it also fixed compilation issues on 4.11+ kernels.

**Comment by kwilczynski** [comment]
@shanonvl thank you so much for the fixed and all the detective work you've done to track the underlying issues. Simply amazing!

**Comment by kwilczynski** [comment]
@shanonvl you should be able to merge changes by yourself now. I hope. :)

File: scripts/ec2/networking.sh (hunk 1 above)
Comment (shanonvl) [reply scripts/ec2/networking.sh:32]: Good point!   I will check it out and configure adaptive rx/tx via ethtool if not.

Comment (kwilczynski) [reply scripts/ec2/networking.sh:32]: Thank you Sir!

I remember having to do this with some versions, which is why we need to confirm, but definitely not a show stopper or otherwise.

I am also not entirely sure why they might have (possibly) retired this module option/parameter. I would need to search through change logs to find out (I will have a look later and report back).

Comment (shanonvl) [reply scripts/ec2/networking.sh:32]: Okay, just grabbed the source for 4.2.1 and confirmed that `InterruptThrottleRate` is still a valid parameter via the README so we should be good to go here.   Let me know if you'd like me to do further testing, otherwise I'll merge.   Thanks!

Comment (kwilczynski) [reply scripts/ec2/networking.sh:32]: @shanonvl thank you! 👍 

Go ahead and merge at your discretion.
